# Generated by Django 5.0.2 on 2026-02-18 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0002_teacher_delete_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_student', models.CharField(max_length=50, unique=True, verbose_name='Matrícula del Alumno')),
                ('career', models.CharField(max_length=255, verbose_name='Carrera')),
                ('semester', models.CharField(max_length=20, verbose_name='Semestre')),
                ('kardex', models.FileField(blank=True, null=True, upload_to='kardex_pdfs/', verbose_name='Kárdex PDF')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
