# Generated by Django 5.0.2 on 2026-02-20 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0004_administrator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Materia')),
                ('code', models.CharField(max_length=20, verbose_name='Código de la Materia')),
                ('department', models.CharField(max_length=255, verbose_name='Departamento/Area')),
                ('color', models.CharField(default='bg-blue-500', max_length=50, verbose_name='Color Materia')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_subjects', to='app_evalpro_api.student', verbose_name='Alumnos Inscritos')),
            ],
        ),
    ]
