# Generated by Django 5.0.2 on 2026-02-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0005_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
