# Generated by Django 5.0.2 on 2026-03-06 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0006_rename_create_by_subject_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(help_text='Fecha y hora en que se abre el examen')),
                ('end_date', models.DateTimeField(help_text='Fecha y hora en que se cierra el examen')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duración del examen en minutos')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='app_evalpro_api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('MATCH', 'Statement Matching'), ('CODE', 'Code Editor')], max_length=10)),
                ('prompt', models.TextField()),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Configuracion espeficica del tipo de pregunta')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de la pregunta en el examen')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_evalpro_api.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app_evalpro_api.question')),
            ],
        ),
    ]
