# Generated by Django 5.0.2 on 2026-03-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0007_exam_question_answeroption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questions_type',
            new_name='question_type',
        ),
    ]
