# Generated by Django 5.0.2 on 2026-03-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0008_rename_questions_type_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Puntaje total del examen', max_digits=5),
        ),
    ]
