# Generated by Django 5.0.2 on 2026-03-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0009_exam_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('closed', 'Closed')], default='draft', help_text='Estado del examen', max_length=20),
        ),
    ]
