# Generated by Django 5.0.2 on 2026-03-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0010_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='partial_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
