# Generated by Django 5.0.2 on 2026-04-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0011_answeroption_partial_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
