# Generated by Django 5.0.2 on 2026-04-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0013_remove_subject_students_subjectenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_subjects', through='app_evalpro_api.SubjectEnrollment', to='app_evalpro_api.student', verbose_name='Alumnos Inscritos'),
        ),
    ]
