# Generated by Django 5.0.2 on 2026-09-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0015_examattempt_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Motivo exacto de la anulación (ej. "Pérdida de foco de ventana")', null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En progreso'), ('completed', 'Completado'), ('annulled_by_fraud', 'Anulado por fraude'), ('needs_grading', 'Pendiente de calificación')], default='in_progress', max_length=20),
        ),
    ]
