# Generated by Django 5.0.2 on 2026-10-08 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0016_examattempt_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='kardex',
        ),
    ]
