# Generated by Django 5.0.2 on 2026-10-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evalpro_api', '0017_remove_student_kardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='is_auto_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
